spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # 도커 빈 DB에 테이블을 자동 생성해줌
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    root: info
    com.codeit.monew: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j